### PR TITLE
Actually sign-extend BitVector

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by christiaanb** [comment]
`BitVector`'s `Num` instance does _unsigned_ arithmetic (see http://hackage.haskell.org/package/clash-prelude-0.11/docs/CLaSH-Sized-BitVector.html#t:BitVector), so `zeroExtend` and `signExtend` should behave the same. Hence, I don't think this patch is correct.

**Comment by strake** [comment]
> BitVector's Num instance does unsigned arithmetic ..., so zeroExtend and signExtend should behave the same.

I'm not sure how this follows. In any case, the comment on `signExtend` says "Add extra sign bits in front of the MSB" so this behavior is a great surprise to me at least. So why have both `zeroExtend` and `signExtend`?

**Comment by christiaanb** [comment]
We have `zeroExtend` because otherwise we would have no "convenient" way to zero-extend a signed representation, as the `resize` function sign-extends signed representations when the result is larger than the argument.

We have the `extend` functions, so that when working in a team (or when reading your own old code), the name conveys to the reader what you were trying to do. Because `resize` can both grow and shrink.

For the `Unsigned` type, `signExtend` also behaves the same as `zeroExtend`. I guess, in hindsight... instead of calling it `signExtend`, I should've called it `extend`. Then there wouldn't be this confusion.

**Comment by strake** [comment]
> We have zeroExtend because otherwise we would have no "convenient" way to zero-extend a signed representation

As it is now, CλaSH has no convenient way to sign-extend an unsigned or sign-agnostic representation.

As a user, i like to have the option whether to consider signedness a property of the types or of the operations, and assumed this is why CλaSH has `BitVector`, `Signed`, and `Unsigned`: `Signed` and `Unsigned` to deal with known signed or unsigned values and imply which operations are signed, and `BitVector` to deal with raw values and exply which operations are signed.

> instead of calling it `signExtend`, I should've called it `extend`.

`Resize` already has a method `extend`, which seems to do exactly this. I think the name "signExtend", as used now, e.g. to zero-extend `BitVectors`, is highly misleading, and the `signExtend` method ought to be modified to sign extend its argument, of any type, or deprecated for `extend`.

**Comment by christiaanb** [comment]
So would you also be in favour of removing `BitVector`'s `Num` instance? I would actually.

**Comment by comonoidial** [comment]
I think all type class methods should have either an obvious type based interpretation or a clear universal semantics. Thus this PR should either be accepted or signExtend be deprecated.

As for BitVector, I think it should be only viewed as a raw sequence of bits, thus no instances for all Num-like classes. However fromInteger should be preserved to keep building a bitvector from a literal value trivial.

**Comment by strake** [comment]
> So would you also be in favour of removing BitVector's Num instance?

Not until we have a sane way to write numeric `BitVector` literals. Num is a shitshow but for now it seems to be the only show in town. That said, we needn't actually re-export `Num` at all, but that's another question altogether.

I think it makes sense to define `(+)`, `(-)`, `(*)` on `BitVector` however, as these operations are the same on signed and unsigned numbers of fixed width, and implementing `(+)` or `(-)` oneself is usually a bad idea, as synthesis tools or VLSI engineers can usually emit more efficient adders than one could write in a HDL.

**Comment by Ericson2314** [comment]
Wait what? The whole time I used CLaSH, I though the signed- and zero- variants were explicity one or the other, and plain "extend" follows from the type.

Maybe call it "msbExtend"? then to be clear on the algorithm regardless of purpose/context?

**Comment by christiaanb** [comment]
I see @strake's point now, and will merge this PR. Sorry for being somewhat dismissive at first, and thanks for convincing me.

**Comment by Ericson2314** [comment]
What about the Unsigned family of types? It's those that make me want to call it `msbExtend` as they technically have no "sign bit".

**Comment by strake** [comment]
> What about the Unsigned family of types?

This patch was for `BitVector` only; `signExtend` on `Unsigned` is unaffected.

**Comment by Ericson2314** [comment]
@strake yeah, I'm thinking that the status quo for `Unsigned` is not ideal either.

**Pull request merged**
