### PR TITLE
Add `safeIndexPow2` to safely index Vecs with 2^n elements

### LINKED ISSUE #17: Add Safe vector indexing
Just as we have pow2 block ram, etc, it would be nice if we had safe pow2 vector indexing.

I was just refactoring one of my processors to change the word size, and some bugs got caught with my tests instead of the type checker because I was using `!!`.

Maybe something like
```haskell
(!!!) :: Integral i
      => KnownNat (2 ^ BitSize i)
      => Vec (2 ^ BitSize i) a
      -> i -> a
(!!!) = (CL.!!)
```
should go in `CLaSH.Sized.Vector`?

Feel free to suggest a different identifier if you like the idea, of course.

### PR DESCRIPTION
**Pull request by Ericson2314**
My only concern is whether it is better to make the index be `Unsigned` or something to avoid negative out-of-bounds.

Fixes #17

### CODE REVIEW

**Comment by christiaanb** [comment]
I think I prefer your suggestion over the current pull-request. If we are going to have a _safe_ indexing function, we might as well go all the way. Also, don't you think that maybe the `Pow2` suffix is too much?

**Comment by Ericson2314** [comment]
Ok, the only complication there is that Unsigned is not currently imported, but I hope it won't introduce a cycle. I figured I'd throw in the -`Pow2` to differentiate from `at` which I hadn't heard of before, and which also is a "safe index", but I'm happy to chuck it.

A third idea that just occurred to me now is to make finite sets a la Agda, and rewrite `at` with it. Then the index given to `at` can be "dynamic", and we can make an `Unsigned n -> Fin (n ^ 2)` conversion.

**Comment by christiaanb** [comment]
Yeah, probably best to update `at` to work on `Fin`, and make the suggested conversion from `Unsigned` to `Fin`. I suggest putting `Fin` in it's own module: `CLaSH.Sized.Fin`.

**Comment by Ericson2314** [comment]
That all sounds good.

**Comment by Ericson2314** [comment]
One last thing, now that we have arbitrary sized naturals in base, we could use them to implement `BitVector`, `Unsigned`, and `Fin`. Also, `index_int` could be `index_word`, and the negative check could be moved to `(!!)`. Then `at` could skip the `< 0` check.

Also, if we made a class like https://hackage.haskell.org/package/nats-0.1/docs/Numeric-Natural-Internal.html#t:Whole (that didn't make it to `base-4.8`, unfortunately), there there would be some use for a power of 2 safe index again.

**Comment by christiaanb** [comment]
What module are these arbitrary size natural ins?

**Comment by Ericson2314** [comment]
https://hackage.haskell.org/package/base-4.8.0.0/docs/Numeric-Natural.html and `GHC.Natural`

**Pull request closed without merging**
