### PR TITLE
Read instances

### PR DESCRIPTION
**Pull request by ggreif**
*This should be mergeable now*, though I suggest squashing on merge.

See issue #51

### CODE REVIEW

**Comment by christiaanb** [comment]
Please also add haddock docs saying that the read instances are not synthesisable.

**Comment by ggreif** [comment]
Added haddocs, please check. Also, what about saturating arithmetic types? `Fixed`?

**Comment by christiaanb** [comment]
The read instance for `Fixed` is good

**Comment by christiaanb** [comment]
Can you rebase+squash to 1 commit when you're finished?

**Comment by ggreif** [comment]
Sure!

**Pull request merged**
