### PR TITLE
Moore Machines

### LINKED ISSUE #15: Moore machine combinatores
We have mealy machines in here, why not more machines? While its not too hard to use the Mealy combinators to make a more machine, I found myself using Moore machines often enough to warrant writing the contaminator. I'd be happy to submit a pull request if you want one.

### PR DESCRIPTION
**Pull request by Ericson2314**
Closes #15

### CODE REVIEW

**Comment by Ericson2314** [comment]
I'm installing the test deps now, so I'd figured I'd let travis get a head start :)

**Comment by christiaanb** [comment]
Thanks for doing this, I'll merge once the test suite passes on travis.

**Comment by Ericson2314** [comment]
I got the fixes.

**Comment by Ericson2314** [comment]
And sure! One less thing that goes in my `Utils` garbage heap :)

**Comment by christiaanb** [comment]
You need to add the module to the .cabal file

**Comment by Ericson2314** [comment]
Oh, forgot to declare the module in cabal.

**Pull request merged**
