### PR TITLE
make mealy inline

### PR DESCRIPTION
**Pull request by ra1u**
INLINABLE does not seems to have desirable effect

### CODE REVIEW

**Comment by Ericson2314** [comment]
I beleive inlinable is for requesting inling per call site, or something like that.

**Comment by ra1u** [comment]
I need to made this change to make mealy (not just mealy') inlined. I am using ghc8 build.

From [doc](https://downloads.haskell.org/~ghc/8.0.1-rc4/docs/html/users_guide/glasgow_exts.html#inlinable-pragma) looks like INLINABLE has no effect at all

> While INLINE says “please inline me”, the INLINABLE says “feel free to inline me; use your discretion”. In other words the choice is left to GHC, which uses the same rules **as for pragma-free functions.** Unlike INLINE, that decision is made at the call site, and will therefore be affected by the inlining threshold, optimisation level etc.

**Comment by Ericson2314** [comment]
Ah ok, my information probably dates back to no inlining across modules by default or something like that. Thanks!

**Comment by thoughtpolice** [comment]
I believe this can be closed now -- mealy should no longer generate modules unnecessarily, and you should be able to precisely control module generation with multiple top entities.

**Pull request closed without merging**
