### PR TITLE
Warning-clean compilation on GHC HEAD

### PR DESCRIPTION
**Pull request by ggreif**
mostly redundant constraints and imports

### CODE REVIEW

**Comment by ggreif** [comment]
oh, and I did not mess with

```
[10 of 42] Compiling CLaSH.Signal.Internal ( src/CLaSH/Signal/Internal.hs, dist/build/CLaSH/Signal/Internal.o )
src/CLaSH/Signal/Internal.hs:447:22: Warning:
    In the use of ‘bitSize’ (imported from Data.Bits):
    Deprecated: "Use 'bitSizeMaybe' or 'finiteBitSize' instead"
```

**Comment by ggreif** [comment]
Regarding those two in `Vector.hs` I'll take those back. Thanks for pointing it out!

**Comment by christiaanb** [comment]
Yeah, I don't know what to do with the `Bits` instance of `Signal'`, perhaps implement `bitSize` as? :

```haskell
bitSize _ = maybe 0 const (bitSizeMaybe (undefined :: a)) 
```

**Comment by christiaanb** [comment]
Thanks for the patch

**Pull request merged**
