### PR TITLE
dfold: provide stepper function with a KnownNat l context

### PR DESCRIPTION
**Pull request by gergoerdi**
See http://stackoverflow.com/a/42643335/477476 for some context.

### CODE REVIEW

**Comment by christiaanb** [comment]
But `SNat l` is a reified `KnownNat l` constraint. So the stepper function passed to `dfold` can just pattern match on the `SNat` constructor to get the `KnownNat l` constraint.

So in your example, you should be able to write `vecAccum` like:

```haskell
vecAcum :: Ord a
        => SNat l
        -> Splitter a
        -> SplitHalf a @@ l                                             -- ^ p @@ l
        -> SplitHalf a @@ (l+1)                                         -- ^ p @@ (l+1)
vecAcum SNat splitter (f, g) = (bitonicSort f g, bitonicMerge g)
```

**Comment by gergoerdi** [comment]
Oh, nice, I didn't realize that was the case! Ticket withdrawn then.

**Comment by christiaanb** [comment]
Please let me know if it doesn't work though!

**Comment by gergoerdi** [comment]
No, it does, I've just updated my answer on SO to use `SNat` to bring `KnownNat l` into scope, and it works as expected.

**Pull request closed without merging**
